### ISSUE TITLE
support for new spaces

### ISSUE THREAD

**Issue by angel-ayala** [AIRLab-POLIMI/mushroom#123]
can you implement or give me some guidance to implement new spaces type like in [Gymnasium](https://gymnasium.farama.org/api/spaces/).

There are some important spaces such as Dict and Tuple which I'm requiring.

Thanks in advance

**Comment by angel-ayala** [comment]
I was looking the implementation of the [Gym environment](https://github.com/MushroomRL/mushroom-rl/blob/dev/mushroom_rl/environments/gym_env.py) and there is a `_convert_gym_space()` method which transfer the Gym spaces to the [Mushroom spaces](https://github.com/MushroomRL/mushroom-rl/blob/master/mushroom_rl/utils/spaces.py) code and comparing with the [Discrete](https://github.com/openai/gym/blob/master/gym/spaces/discrete.py) and [Box](https://github.com/openai/gym/blob/master/gym/spaces/box.py)'s from Gym library.

So, I was wondering the need to do this transfer spaces because the only enhancement achieve is to store the object as `Serializable`. Can this be done using a wrapper adding the `self._add_save_attr()` method use for the respective attributes presentes in the Gym spaces?

**Comment by davide-tateo90** [comment]
dear @angel-ayala ,
We do this transfer of spaces because we think the Tuple and Dict environments are not well-suited for reinforcement learning state space. Thus we decided not to support these state spaces for the two following reasons:

1) The tuple is nothing else than a finite MDP environment with coordinates. If the MDP is too big, you should not use tuples, but the Box environment (e.g. if you want a generalization in coordinates). NB: if you use tuples, you cannot solve finite MDPs using mushroom finite agents, as they use a single index to discriminate finite states. If you want to use a continuous algorithm, you can just put the tuples inside a vector using box state (the fact that the coordinates are discrete is completely irrelevant)

2) The dict state space is irrelevant, as you can stack together the elements of the environment and create a vector.
If you want to use dictionary output, you can simply return data using the info dictionary, which is already passed to the fit method of the environment.

Side note about gymnasium: we are still not sure when (and if) we will support it. The API of gym was breaking too much to be of any use (indeed we stopped the support at gym 0.24.1), and until gymnasium is stable and not breaking every release, we are not going to support it. However, making an interface based on the gym one is pretty trivial.

It would be instead interesting to support more complex state space, such as graphs. This requires however support for graph neural networks and a bit of software engineering, and is not planned in the short future.
