### ISSUE TITLE
Some function approximators that do not come from sklearn cannot be used

### ISSUE THREAD

**Issue by cantor-dust** [AIRLab-POLIMI/mushroom#77]
Hi,

I am working on a library that uses MushroomRL at its core. 

I want to be able to use any kind of function approximator, even those that do not come from sklearn but this is not always possible. 

The problem is in the module: regressor.py ([https://github.com/MushroomRL/mushroom-rl/blob/dev/mushroom_rl/approximators/regressor.py](url)). Specifically in the block of lines 49-51 in which you add to the params dictionary the input_shape and the output_shape, like so:
`params['input_shape'] = input_shape`
 `params['output_shape'] = output_shape`

You do this only if the approximator module does not start with 'sklearn'. 

Now suppose that I use XGBoostRegressor as approximator: everything runs smoothly, I just get a warning from xgboost saying `Parameters: { input_shape, output_shape } might not be used` 

This is all fine until I start using other approximators, such as CatBoostRegressor: here the initialisation of the object CatBoostRegressor fails: `__init__() got an unexpected keyword argument 'input_shape'`

Obviously I could simply change the current if condition, from: `if not approximator.__module__.startswith('sklearn')` to include also other modules, but this is just a bad work-around.

Are you already planning a fix so that it will be possible to use other approximators such as CatBoostRegressor?

Thanks.

**Comment by davide-tateo90** [comment]
Dear @cantor-dust ,
Unfortunately, we cannot support any library possible for regressors.
If you want to suggest a specific, well-used library that you want us to add to have the same treatment as sklearn, we could add it in the condition. 
Otherwise, I suggest implementing a wrapper class for your chosen library to correctly process the instantiation (and, maybe, also the fit).

Unfortunately, the input shape is fundamental for neural networks and linear approximations, ad we would like to avoid using reflection to inspect the signature of the constructor.

**Comment by davide-tateo90** [comment]
closing as there was no further input on the topic
